#spring.datasource.url=jdbc:mysql://localhost:3306/blog
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://ec2-3-223-169-166.compute-1.amazonaws.com:5432/d6ep1ipslv9apn
spring.datasource.username=mhxjccxqwjgdhd
spring.datasource.password=2988884311b55ed213bd9b36bb38eb55249309ef30543fcd551e4bceddb17310
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true